# Generated by Django 2.2.10 on 2020-02-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='hgh',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
