# Generated by Django 2.2.10 on 2020-02-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_test_hgh"),
    ]

    operations = [
        migrations.RenameField(model_name="test", old_name="hgh", new_name="fhfhg",),
    ]
