# Generated by Django 2.2.10 on 2020-02-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200227_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='vhb',
            field=models.DateField(blank=True, null=True),
        ),
    ]
